baseURL = "https://nextgenfeed.info/"
languageCode = "en-us"
title = "NextGenFeed"
theme = "mainroad"

# Включаем автоматическую генерацию robots.txt для SEO
enableRobotsTXT = true

# Настройки внешнего вида (Deep Tech)
[params]
  highlightColor = "#1a5fb4" # Глубокий синий акцентный цвет
  readmore = true # Кнопка "Читать далее" для красивого превью

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
	name = "Contact"
	url = "/contact/"
	weight = 3
