name: Deploy Hugo site to Pages

on:
  schedule:
    - cron: '*/30 * * * *'  # Запуск каждые 30 минут
  push:
    branches: ["main"]
    
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Глобальные переменные для исправления предупреждений Node.js
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Включаем загрузку тем, если они подключены как субмодули
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --minify 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
